============================= test session starts ==============================
platform linux -- Python 3.11.7, pytest-7.4.4, pluggy-1.3.0
rootdir: /home/runner/work/psnawp/psnawp
configfile: pyproject.toml
testpaths: tests
plugins: vcr-1.0.2, cov-4.1.0
collected 69 items

tests/unit_tests/test_authenticator.py .                                 [  1%]
tests/unit_tests/test_client.py .................                        [ 26%]
tests/unit_tests/test_game_title.py .........                            [ 39%]
tests/unit_tests/test_group.py .........                                 [ 52%]
tests/unit_tests/test_search.py ...                                      [ 56%]
tests/unit_tests/test_user.py ............................               [ 97%]
tests/unit_tests/test_utils_misc.py .F                                   [100%]

=================================== FAILURES ===================================
________________ test_play_duration_to_timedelta_invalid_inputs ________________

    def test_play_duration_to_timedelta_invalid_inputs():
        assert play_duration_to_timedelta(None) == timedelta(hours=0, minutes=0, seconds=0)
>       assert play_duration_to_timedelta("PT90H23M22S23MS") == timedelta(hours=0, minutes=0, seconds=0)
E       AssertionError: assert datetime.timedelta(days=3, seconds=66202) == datetime.timedelta(0)
E        +  where datetime.timedelta(days=3, seconds=66202) = play_duration_to_timedelta('PT90H23M22S23MS')
E        +  and   datetime.timedelta(0) = timedelta(hours=0, minutes=0, seconds=0)

tests/unit_tests/test_utils_misc.py:18: AssertionError
-------- generated xml file: /home/runner/work/psnawp/psnawp/pytest.xml --------

---------- coverage: platform linux, python 3.11.7-final-0 -----------
Name                                                    Stmts   Miss  Cover
---------------------------------------------------------------------------
src/psnawp_api/__init__.py                                  3      0   100%
src/psnawp_api/core/__init__.py                             0      0   100%
src/psnawp_api/core/authenticator.py                       46      3    93%
src/psnawp_api/core/psnawp_exceptions.py                    9      0   100%
src/psnawp_api/models/__init__.py                           0      0   100%
src/psnawp_api/models/client.py                            70      0   100%
src/psnawp_api/models/game_title.py                        22      0   100%
src/psnawp_api/models/group.py                             52      0   100%
src/psnawp_api/models/listing/__init__.py                   0      0   100%
src/psnawp_api/models/listing/listing_generator.py         36      5    86%
src/psnawp_api/models/listing/pagination_arguments.py      15      0   100%
src/psnawp_api/models/search.py                            22      0   100%
src/psnawp_api/models/title_stats.py                       84     23    73%
src/psnawp_api/models/trophies/__init__.py                  0      0   100%
src/psnawp_api/models/trophies/trophy.py                  112      0   100%
src/psnawp_api/models/trophies/trophy_constants.py         25      0   100%
src/psnawp_api/models/trophies/trophy_group.py             89      0   100%
src/psnawp_api/models/trophies/trophy_summary.py           25      0   100%
src/psnawp_api/models/trophies/trophy_titles.py            86      0   100%
src/psnawp_api/models/trophies/utility_functions.py         7      0   100%
src/psnawp_api/models/user.py                              71      0   100%
src/psnawp_api/psnawp.py                                   35      0   100%
src/psnawp_api/utils/__init__.py                            0      0   100%
src/psnawp_api/utils/endpoints.py                           2      0   100%
src/psnawp_api/utils/misc.py                               31      1    97%
src/psnawp_api/utils/request_builder.py                    72     15    79%
---------------------------------------------------------------------------
TOTAL                                                     914     47    95%

=========================== short test summary info ============================
FAILED tests/unit_tests/test_utils_misc.py::test_play_duration_to_timedelta_invalid_inputs - AssertionError: assert datetime.timedelta(days=3, seconds=66202) == datetime.timedelta(0)
 +  where datetime.timedelta(days=3, seconds=66202) = play_duration_to_timedelta('PT90H23M22S23MS')
 +  and   datetime.timedelta(0) = timedelta(hours=0, minutes=0, seconds=0)
========================= 1 failed, 68 passed in 3.04s =========================
